name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: 'Maven: Build and upload artifact'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Magnolia bundle
        run: mvn package -B -U

      - name: Build Magnolia Docker Image
        run: mvn -B -Dgithub-registry=${{github.repository_owner}} docker:build

      - name: Push Magnolia Docker Image
        run: mvn -B -Ddocker.username=${{secrets.PACKAGE_USER}} -Ddocker.password=${{secrets.PACKAGE_TOKEN}} -Dgithub-registry=${{github.repository_owner}} docker:push


  helm-lint:
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./helm-chart
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install github-magnolia-docker ./helm-chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'
